### ISSUE TITLE
WebPageTest - TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jangrewe** [sitespeedio/sitespeed.io#1447]
I'm running SSIO with WPT against a private instance which works fine by itself, but when SSIO gets the results back, if throws this error:
```
[2017-02-09 19:30:32] Got https://quazer.com/ analysed from http://webpagetest.example.com
[2017-02-09 19:30:33] Error creating WebPageTest result  TypeError: Cannot read property 'toLowerCase' of undefined
    at analyzer.analyzeUrl.tap (/usr/src/app/lib/plugins/webpagetest/index.js:101:60)
    at callbackYield (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:152:14)
From previous event:
    at Object.processMessage (/usr/src/app/lib/plugins/webpagetest/index.js:90:12)
    at queue.process (/usr/src/app/lib/support/queueHandler.js:157:57)
    at drainItem (/usr/src/app/node_modules/concurrent-queue/index.js:92:21)
    at Immediate.drain (/usr/src/app/node_modules/concurrent-queue/index.js:73:84)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
    at Unzip.Readable.on (_stream_readable.js:687:35)
    at zlibBuffer (zlib.js:195:10)
    at Object.exports.unzip (zlib.js:147:10)
    at IncomingMessage.onEnd (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:125:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at IncomingMessage.Readable.on (_stream_readable.js:687:35)
    at ClientRequest.getResponse (/usr/src/app/node_modules/webpagetest/lib/webpagetest.js:113:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:363:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```
This happens with the Docker image tagged as `4.3.9`

The WPT Location has `connectivity=Native` set, and i'm also passing `--webpagetest.connectivity Native` to SSIO.

**Comment by jangrewe** [comment]
I think the fallback to `native`, like proposed in #713, would be the easiest fix for this issue. I can't find `LAN` in WPT's `connectivity.ini`, so i'm guessing they renamed it to `Native` now?

**Comment by soulgalore** [comment]
Hey @jangrewe 
hmm I've seen problems with connectivity a couple of these the last four years, and I think I fixed it before in older versions but 4.0 was a complete rewrite and I must have missed that.

Do you remember, is there a default config that you use in WPT or did you setup locations by yourself? The reason I ask is because if you setup AWS agent, everything works fine (the default config there is ok). Maybe we could find the right place in WPT change the default config there too :)

Best
Peter

**Comment by jangrewe** [comment]
I'm using their stock config and just replace the locations.ini with this:
```
[locations]
1=Quazer_Office
default=Quazer_Office

[Quazer_Office]
1=Win10
label="Quazer Office - Berlin, DE"
group=Local

[Win10]
browser=Chrome,Firefox
label="Windows 10 VM"
connectivity=Native
```
In their stock locations.ini, they don't set any `connectivity`, but i have to set it to `Native` because i'm using a Win10 x64 VM, and that doesn't support traffic shaping. I guess if you don't explicitly set one, they fall back to `Cable` and that's what gets reported in the results then.

**Comment by soulgalore** [comment]
I see, I pushed a fix for it now, I wanna do the release this weekend but we are behind with docs for the new functionalities.

**Comment by jangrewe** [comment]
Thanks, i'll build a Docker image and will report back!

**Comment by jangrewe** [comment]
Yay, it works now! =)

One last, semi-unrelated question: I'm setting `--webpagetest.private false`, but the results from SSIO still don't show up on the Test History page - or is that a misunderstanding on my side?

**Comment by soulgalore** [comment]
You can have it private, I think that flag is only for the public instance. The thing in search is that you need to click on "Show tests from all users" did you do that?

**Comment by jangrewe** [comment]
Oh, that's a bit embarrassing now... ;-)

Alright then, i'm a happy camper now, Thanks a lot for the fix - and your work in general!
