### ISSUE TITLE
Make it possible for plugins to add it metrics to the budget

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/sitespeed.io#1825]
As a plugin you can push metrics to the HTML plugin, we should do the same for the budget plugin.

**Comment by soulgalore** [comment]
This is fixed.

**Comment by zunjooo** [comment]
Hello, 

I added gpsi metric to config.json file with all my budget metrics but I still can't see gpsi score in generated HTML result's budget section... I just see gpsi section inside Pages -> Page summary

I'm using sitespeed version 6.5.1.

**Comment by soulgalore** [comment]
Hi @zunjooo could it be that I missed added it so the plugin don't register for a budget, let me check that later today.

Best
Peter

**Comment by soulgalore** [comment]
It was implemented in sitespeed.io (this issue) but all plugins needs to register for budget, the branch was there in the gpsi plugin but not merged. I merged it now so of you update the gpsi plugin I hope it will work!
Best
Peter

**Comment by zunjooo** [comment]
It's working! Thank you for a quick response as always! :)

Best,
Vanja
