### ISSUE TITLE
Undefined value found at path 'thirdParty.cookieStats' for 'pagexray.pageSummary' message (url = undefined)

### ISSUE THREAD

**Issue by geoffrey-brier** [sitespeedio/sitespeed.io#2463]
Hi there,

First of all, thanks for the wonderful tool ;)

I'm running sitespeed on my Ubuntu 18.04 (bionic) via Docker and I have this error : 

```
Undefined value found at path 'thirdParty.cookieStats' for 'pagexray.pageSummary' message (url = undefined)
```

Here is the full output along with the command line I'm using :

```
$> docker run --rm -v "$(pwd)":/sitespeed.io sitespeedio/sitespeed.io:8.15.2 --graphite.host=XXX --graphite.httpHost=80 --chrome.timeline=true --firstParty=.*.online.net -n 1 https://www.online.net/en -v
Google Chrome 74.0.3729.131 
Mozilla Firefox 66.0.4
[2019-05-20 15:04:23] INFO: [sitespeedio] Versions OS: linux 4.15.0-50-generic nodejs: v10.13.0 sitespeed.io: 8.15.2 browsertime: 4.9.1 coach: 3.4.0
[2019-05-20 15:04:23] DEBUG: [sitespeedio.plugin.graphite] Setting up Graphite XXX for namespace sitespeed_io.default
[2019-05-20 15:04:23] DEBUG: [browsertime] Running with options: {
  "scripts": [],
  "iterations": 1,
  "delay": 0,
  "videoParams": {
    "addTimer": true,
    "filmstripFullSize": false,
    "createFilmstrip": true,
    "framerate": 30,
    "crf": 23,
    "filmstripQuality": 75
  },
  "statistics": true,
  "browser": "chrome",
  "connectivity": {
    "profile": "native",
    "engine": "external"
  },
  "screenshot": true,
  "screenshotParams": {
    "type": "png",
    "png": {
      "compressionLevel": 6
    },
    "jpg": {
      "quality": 80
    },
    "maxSize": 2000
  },
  "viewPort": "1366x708",
  "xvfbParams": {
    "display": 99
  },
  "spa": false,
  "pageCompleteCheckInactivity": false,
  "visualMetrics": true,
  "visualElements": false,
  "video": true,
  "firefox": {
    "nightly": false,
    "beta": false,
    "developer": false,
    "acceptInsecureCerts": false,
    "collectMozLog": false,
    "includeResponseBodies": "none"
  },
  "chrome": {
    "timeline": true,
    "collectNetLog": false,
    "collectConsoleLog": false,
    "cdp": {
      "performance": true
    }
  },
  "headless": false,
  "docker": "true",
  "xvfb": "true",
  "pageCompleteWaitTime": 5000,
  "pageLoadStrategy": "normal",
  "verbose": 1,
  "mobile": false,
  "screenshotType": "png",
  "coach": true,
  "resultDir": "/sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23"
}
[2019-05-20 15:04:23] INFO: [browsertime] Running tests using Chrome - 1 iteration(s)
[2019-05-20 15:04:24] INFO: [browsertime.command.measure] Testing url https://www.online.net/en iteration 1
[2019-05-20 15:04:24] DEBUG: [browsertime.video] Add orange color
[2019-05-20 15:04:24] DEBUG: [browsertime.video] Started ffmpeg with -hide_banner -video_size 1366x642 -f x11grab -framerate 30 -probesize 1M -y -draw_mouse 0 -i :99.0+0,66 -codec:v libx264rgb -crf 0 -preset ultrafast -vf pad=ceil(iw/2)*2:ceil(ih/2)*2 /tmp/browsertime-sTZHpG/x11.mp4
[2019-05-20 15:04:25] DEBUG: [browsertime] Waiting for script pageCompleteCheck at most 300000 ms
[2019-05-20 15:04:30] DEBUG: [browsertime.video] Stop screen recording
[2019-05-20 15:04:30] DEBUG: [browsertime.video] Stopped ffmpeg
[2019-05-20 15:04:30] DEBUG: [browsertime.video] Converting video to viewable format with args ["-nostdin","-i","/tmp/browsertime-sTZHpG/x11.mp4","-c:v","libx264","-crf",23,"-preset","medium","-vf","format=yuv420p","/sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23/pages/www.online.net/en/data/video/1.mp4"]
[2019-05-20 15:04:31] DEBUG: [browsertime.video] Writing to /sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23/pages/www.online.net/en/data/video/1.mp4
[2019-05-20 15:04:32] DEBUG: [browsertime.chrome] Getting performance logs from Chrome
[2019-05-20 15:04:33] DEBUG: [browsertime] Telling browser to quit.
[2019-05-20 15:04:33] DEBUG: [browsertime.video] Running visualMetrics
[2019-05-20 15:04:33] DEBUG: [browsertime.video] Running visualmetrics.py --dir /sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23/pages/www.online.net/en/data/video/images/1 --video /sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23/pages/www.online.net/en/data/video/1.mp4 --orange --perceptual --force --renderignore 5 --json --viewport -q 75 --logfile /sitespeed.io/sitespeed-result/www.online.net/2019-05-20-15-04-23/pages/www.online.net/en/data/video/1.visualmetrics.log -vvvv
[2019-05-20 15:04:36] DEBUG: [browsertime.video] visualmetrics.py output:{"SpeedIndex": 519, "FirstVisualChange": 333, "LastVisualChange": 767, "videoRecordingStart": 467, "PerceptualSpeedIndex": 551, "VisualProgress": "0=0%, 333=36%, 367=37%, 467=42%, 600=42%, 633=95%, 667=96%, 733=98%, 767=100%"}
[2019-05-20 15:04:36] DEBUG: [browsertime.video] Collected metrics {"SpeedIndex":519,"FirstVisualChange":333,"LastVisualChange":767,"videoRecordingStart":467,"PerceptualSpeedIndex":551,"VisualProgress":"0=0%, 333=36%, 367=37%, 467=42%, 600=42%, 633=95%, 667=96%, 733=98%, 767=100%"}
[2019-05-20 15:04:37] DEBUG: [browsertime] Telling browser to quit.
[2019-05-20 15:04:37] INFO: [browsertime] https://www.online.net/en 35 requests, 873.29 kb, backEndTime: 89ms, firstPaint: 311ms, firstVisualChange: 333ms, DOMContentLoaded: 440ms, Load: 754ms, speedIndex: 519, visualComplete85: 633ms, lastVisualChange: 767ms, rumSpeedIndex: 311
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [root] Undefined value found at path 'thirdParty.cookieStats' for 'pagexray.pageSummary' message (url = undefined)
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [plugin.browsertime] Generate summary metrics from Browsertime
[2019-05-20 15:04:37] DEBUG: [plugin.coach] Generate summary metrics from the Coach
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [plugin.pagexray] Generate summary metrics from PageXray
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.graphite] Send data to Graphite XXX
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.html] Render HTML for 1 page(s) 
[2019-05-20 15:04:37] DEBUG: [sitespeedio.plugin.html] Render summary page pages
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page index
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page detailed
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page domains
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page assets
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page toplist
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render summary page help
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render URL page index
[2019-05-20 15:04:38] DEBUG: [sitespeedio.plugin.html] Render URL run page 1
```

Hope this is gonna help.

**Comment by soulgalore** [comment]
Hi @geoffrey-brier thanks for the kind words :)
 
It's a warning and I need to dig into the reason (it's something with that page that we don't handle correctly). I'll look into it after I've pushed the new release later today/tomorrow (since it's not a breaking thing).

Best
Peter

**Comment by geoffrey-brier** [comment]
Hi @soulgalore ,

Did you had time to investigate ?

FYI, I just upgraded to the latest version and I still have the same problem.

**Comment by soulgalore** [comment]
No I haven't spent any time on it since its a warning meaning (I think) its some dirty data on that site that we don't handle.
