### ISSUE TITLE
Stuck run with enabled lighthouse on a new version

### ISSUE THREAD

**Issue by Amerousful** [sitespeedio/sitespeed.io#4000]
### Have you read the documentation?

- [X] Yes, I've read the [how to make a reproducable bug guide](https://www.sitespeed.io/documentation/sitespeed.io/bug-report/)
- [X] Yes, I've read the [how to debug my script guide](https://www.sitespeed.io/documentation/sitespeed.io/scripting/#debug)

### URL

https://www.sitespeed.io/

### What are you trying to accomplish

I ran a simple test with a new version `30.2.0` and it stucks. Docker image: `sitespeedio/sitespeed.io:30.2.0-plus1`. I checked with the previous version `sitespeedio/sitespeed.io:30.1.0-plus1`, and everything is okay.

### What browser did you use?

Chrome

### How to reproduce

```shell
docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:30.2.0-plus1 https://www.sitespeed.io/ -n 1 -v
```

### Log output

```shell
[2023-11-03 12:26:26] INFO: [sitespeed.io.plugin.lighthouse] Start collecting Lighthouse result for https://www.sitespeed.io/
[2023-11-03 12:26:26] DEBUG: [sitespeed.io.plugin.lighthouse] Lighthouse flags [
  {},
  {
    "extends": "lighthouse:default",
    "settings": {
      "maxWaitForFcp": 15000,
      "maxWaitForLoad": 35000,
      "formFactor": "desktop",
      "throttling": {
        "rttMs": 40,
        "throughputKbps": 10240,
        "cpuSlowdownMultiplier": 1,
        "requestLatencyMs": 0,
        "downloadThroughputKbps": 0,
        "uploadThroughputKbps": 0
      },
      "screenEmulation": {
        "mobile": false,
        "width": 1350,
        "height": 940,
        "deviceScaleFactor": 1,
        "disabled": false
      },
      "emulatedUserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
      "skipAudits": [
        "uses-http2",
        "bf-cache"
      ]
    }
  },
  [
    "--headless=new",
    "--no-sandbox",
    "--ignore-certificate-errors"
  ]
] , config undefined , Chrome flags undefined
*HERE STUCKS*
```

**Comment by soulgalore** [comment]
Thank you @Amerousful for reporting! Yes I get the same in the Docker container. Lighthouse was updated to 11.3.0 in that release. What's strange is that it passed in our GitHub Action and when I run it directly using NodeJS it works. In the container it fails.  Checking https://github.com/GoogleChrome/lighthouse/releases/tag/v11.3.0 it seems there's new version of  puppeteer  in that release, I wonder if that could be the issue? Hmm.

**Comment by Amerousful** [comment]
You're welcome!) Yep, initially I also had concern about NodeJs version... But yes, I agree, seems like that there's some problem in the Lighthouse...

**Comment by soulgalore** [comment]
When I wait a while I get PROTOCOL_TIMEOUT, I think maybe Chrome suddenly needs disable-dev-shm-usage fro running in Docker, let me try that.

**Comment by Amerousful** [comment]
Oh, I tried different versions with my testing aim website, but I always got this error `PROTOCOL_TIMEOUT`.With manually run Lighthouse there weren't any errors.
At the same time, with `https:///sitespeed.io` I didn't catch any problem.

**Comment by soulgalore** [comment]
I'm not sure how Chrome handles that internally. I just released 30.2.1 with that extra flag and that seems to fix it for me, hope it works for you!

**Comment by Amerousful** [comment]
Wow! Amazing fix speed, thanks! I'm trying it

**Comment by Amerousful** [comment]
I still have the same problem (I don't mean a `PROTOCOL_TIMEOUT`).
It's really freezing and stuck, because I waited 5-10 min, and even CPU usage is low
<img width="1512" alt="image 739" src="https://github.com/sitespeedio/sitespeed.io/assets/22199881/71c0a20b-91c4-4afa-be90-813fb7a31899">
<img width="1512" alt="image 740" src="https://github.com/sitespeedio/sitespeed.io/assets/22199881/b6cbb5dd-a688-4f6c-a27e-2eea9cafd646">

**Comment by Amerousful** [comment]
Checked all Lighthouse `11.x` versions and it doesn't work. `10.x` works!

**Comment by Amerousful** [comment]
@soulgalore I found! You was right, it's a puppeteer!!! Several hours of debugging and struggling. 
https://github.com/GoogleChrome/lighthouse/pull/15331/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R169

I downgraged a puppeteer version which was in Lighthouse v10.4.0 and it works now. If you wish, I can make a PR with this fix.
<img width="753" alt="image 742" src="https://github.com/sitespeedio/sitespeed.io/assets/22199881/e8339886-fe84-4570-8583-5d105d0587f9">

**Comment by soulgalore** [comment]
Hi @Amerousful aha cool, thanks for investigating. Yes, if you can do that it would be great. 

Different versions of puppeteer uses different Google versions (at least I think) so it would be good to give the feedback to the puppeteer/lighthouse team so they can fix the root cause.

**Comment by Amerousful** [comment]
@soulgalore Hey) Deel, I'm gonna create a PR with this "hot fix", thx!
Yes, I'm in the middle of doing it, and trying to debug what the root cause in puppeteer/lighthouse.

**Comment by Amerousful** [comment]
Here you are https://github.com/sitespeedio/plugin-lighthouse/pull/123

**Comment by Amerousful** [comment]
I hope I provided enough information https://github.com/GoogleChrome/lighthouse/issues/15588

**Comment by soulgalore** [comment]
Thanks for the fixes.
