### ISSUE TITLE
Timed out waiting for the WebDriver server at http://127.0.0.1:XXXXX/

### ISSUE THREAD

**Issue by badrinathvm** [sitespeedio/sitespeed.io#635]
Facing time out waiting for Webdriver server in Red Hat , error running browser time, attached below screen shot
![screen shot 2015-04-02 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/1479179/6974698/c191b106-d949-11e4-94fa-b95f9acef870.png)

**Comment by badrinathvm** [comment]
issue i shappening only for Chrome browser

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
yep so it happening randomly right? Or is it the first time? We seen this issue before (the random one)and it is an issue with Chromedriver/NodeJS-Selenium version, we have reported to the Selenium team but I guess we should talk to them again.

@tobli thinking we should try run using the selenium jar server to see if we get the same problem, maybe it is a Selenium-NodeJS thing? I can check on Sunday if I can implement a generic solution to run the selenium jar for whatever browser or do you see any problem with it?

Best
Peter

**Comment by badrinathvm** [comment]
When i schedule for 5 runs , only first run will be success for next runs it fails mentioning time out.

This happens only in Red hat , in MAc it works excellent. Can i know the procedure how to run with selenium jar ? 

This would help me a lot.

**Comment by soulgalore** [comment]
Hey @badrinathvm 
we pushed a new release today, we are testing running on the selenium jar right now bit it will take some time if we know if it works better. If you want to try it out, update to the latest sitespeed.io, create a file *btconf.json* with the following content:
<pre>
{
 "seleniumServer": "http://localhost:4444/wd/hub"
}
</pre>
and download and start the selenium standalone server 2.45  (http://www.seleniumhq.org/download/) and run sitespeed with the extra parameter: 
<pre> 
--btConfig btconf.json
</pre>

**Comment by badrinathvm** [comment]
Let me give a try too . Please you guys also update the status once tested.

**Comment by Dennis-Richard** [comment]
Hey Guys,
I did try using the selenium standalone server apparently I still see the timeout issue. Could you please provide your suggestion?

-Dennis

**Comment by soulgalore** [comment]
Hi @Dennis-Richard ,
what OS are you using? And how often does it happen? There are a couple of instability issues with selenium on different Linux flavours (both Chrome & Firefox). We are working on a new version where we will be able to catch the problems better (and there are also fixes in the coming Selenium version) and the more info you can give us the better, is it exactly the same error as @badrinathvm or do you get different errors? 

Best
Peter

**Comment by badrinathvm** [comment]
Yes it's the same issue. Can we upgrade to sitespeed.io to latest versions and try ? 

Current version is 3.2.6

**Comment by soulgalore** [comment]
Hi @badrinathvm ,
no, the only thing on version 3.2.7 is that you can configure the selenium servers without a JSON file <code>--seleniumServer</code>. However, when we been running Chrome using Ubuntu we get Chrome errors like Chrome crashing but haven't seen the Timed Out Error. Could you share exact how you are running so I can set it up on a server & test, you can email me peter[at]soulgalore[dot]com? 

Best
Peter

**Comment by soulgalore** [comment]
Hi again,
so are you really sure you get the same error when supplying the selenium jar? When I run it works, maybe if you could try with the 3.2.7 and supply the *seleniumServer* parameter or try one of our Docker images: https://registry.hub.docker.com/repos/sitespeedio/

Best
Peter

**Comment by badrinathvm** [comment]
Trying today , will keep you posted on the result .

**Comment by Dennis-Richard** [comment]
Hey Guys,
I still have this issues, is there anything you guys can suggest?
Regards,
Dennis

**Comment by soulgalore** [comment]
Hey Dennis,
and you use a standalone selenium server? Using the standalone it will use the same port all over again and that seems to work better. Could you share the logs you get when you run? Then we can add issue at Selenium.

You can use our Docker image: https://registry.hub.docker.com/u/sitespeedio/sitespeed.io/ and run it with the included selenium server, we have been using it quite much and haven't seen that error since we started using the selenium jar.

Best
Peter

**Comment by badrinathvm** [comment]
I configured Json and downloaded selenium server 2.45 using below command to execute now 

sitespeed.io -u "http://www1.qa11codemacys.fds.com/shop/product/mac-eye-shadow-0.05-oz?ID=106344" --wptHost www.webpagetest.org --wptKey XXXXX -b chrome -d 0 -n 10 --btConfig btconf.json

**Comment by badrinathvm** [comment]
I performed below steps 

npm install selenium-standalone@latest -g
selenium-standalone install
selenium-standalone start

and then configured  btconfig.json  with below details

{
 "seleniumServer": "http://127.0.0.1:4444/wd/hub"
}


and then executed  site speed command 

sitespeed.io -u "http://www1.qa11codemacys.fds.com/shop/product/mac-eye-shadow-0.05-oz?ID=106344" --wptHost www.webpagetest.org --wptKey XXXXX -b chrome -d 0 -n 10 --btConfig btconf.json

Facing below issue again 


![screen shot 2015-04-29 at 11 02 35 am](https://cloud.githubusercontent.com/assets/1479179/7397691/0a559aae-ee5f-11e4-8020-126178da2d2b.png)

**Comment by soulgalore** [comment]
Hey @badrinathvm ,  I think something is wrong with the config because the error points out port 50928, but it should be 4444.

Just to make it easy, download the selenium standalone jar and start it (you can see here how we do it in our docker files: https://github.com/sitespeedio/sitespeed.io-docker/blob/master/chrome/scripts/start.sh

Then (if you are using 3.2.7 or later) please use <code>--seleniumServer</code> to configure the server, run it like this:
<pre>
sitespeed.io -u "http://www1.qa11codemacys.fds.com/shop/product/mac-eye-shadow-0.05-oz?ID=106344" --wptHost www.webpagetest.org --wptKey XXXXX -b chrome -d 0 -n 10 --seleniumServer http://127.0.0.1:4444/wd/hub
</pre>

Best
Peter

**Comment by badrinathvm** [comment]
My Linux box has 3.2.5 , 

Let me update to latest version and give a try with --seleniumServer http://127.0.0.1:4444/wd/hub

**Comment by KeidyGibson01** [comment]
I use selenium webdriverjs and i have this same problem but I can not find the rotractor-conf.js

**Comment by soulgalore** [comment]
Closing old 3.x issues. Please reopen if you this still is an issue for 4.0.

**Comment by cbaron** [comment]
I think we should reopen this issue.

```
"dependencies": {
    "chromedriver": "^80.0.1",
    "geckodriver": "^1.19.1",
    "jest": "^25.1.0",
    "selenium-webdriver": "^4.0.0-alpha.5"
  },
```

Running locally on my machine works, but when on bitbucket pipeline I see:

```
HEADLESS=true yarn testApp
yarn run v1.22.0
$ cd apps/app-tester && yarn test
$ jest
(node:106) UnhandledPromiseRejectionWarning: Error: Timed out waiting for the WebDriver server at http://127.0.0.1:55358/
(node:106) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:106) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:106) UnhandledPromiseRejectionWarning: Error: Timed out waiting for the WebDriver server at http://127.0.0.1:55358/
```
